In [50]:
import pandas as pd
import numpy as np
from scipy.io import loadmat
import statsmodels.api as sm

dataset_mat = loadmat("olympics.mat")
dataset_mat.keys()
male100_gold = dataset_mat['male100'].transpose()[1][:]
male100_year = dataset_mat['male100'].transpose()[0][:]
male100_year = sm.add_constant(male100_year)
female100_gold = dataset_mat['female100'].transpose()[1][:]
female100_year = dataset_mat['female100'].transpose()[0][:]
female100_year = sm.add_constant(female100_year)
print(dataset_mat['female100'])

male100_weights = np.matmul(np.linalg.inv(np.matmul(male100_year.transpose(), male100_year)),np.matmul(male100_year.transpose(), male100_gold))
print("Male 100 Meter Weights")
print(male100_weights)
female100_weights = np.matmul(np.linalg.inv(np.matmul(female100_year.transpose(), female100_year)),np.matmul(female100_year.transpose(), female100_gold))
print("Female 100 Meter Weights")
print(female100_weights)

[[1928.     12.2    12.3    12.3 ]
 [1932.     11.9    11.9    12.  ]
 [1936.     11.5    11.7    11.9 ]
 [1948.     11.9    12.2    12.2 ]
 [1952.     11.5    11.8    11.9 ]
 [1956.     11.5    11.7    11.7 ]
 [1960.     11.     11.3    11.3 ]
 [1964.     11.4    11.6    11.6 ]
 [1968.     11.     11.1    11.1 ]
 [1972.     11.07   11.23   11.24]
 [1976.     11.08   11.13   11.17]
 [1980.     11.06   11.07   11.14]
 [1984.     10.97   11.13   11.16]
 [1988.     10.54   10.83   10.85]
 [1992.     10.82   10.83   10.84]
 [1996.     10.94   10.94   10.96]
 [2000.     11.12   11.18     nan]
 [2004.     10.93   10.96   10.97]
 [2008.     10.78   10.98   10.97]]
Male 100 Meter Weights
[ 3.64164559e+01 -1.33308857e-02]
Female 100 Meter Weights
[ 4.09241546e+01 -1.50718122e-02]
